"""add genre to books, quantity and total_price to orders

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-18 23:46:36.968785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic — adjusted by hand (see note below) ###
    op.add_column('books', sa.Column('genre', sa.String(length=100), nullable=True))
    # `quantity` is NOT NULL, but this table may already have rows (orders
    # placed before this migration existed). A bare NOT NULL ADD COLUMN would
    # fail on those rows, so we give it a `server_default` — MySQL/SQLite
    # backfill every existing row with 1 (matching the model's Python-side
    # default) at ALTER time. New inserts still go through the ORM default.
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('orders', sa.Column('total_price', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'quantity')
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###
